theme: jekyll-theme-cayman
title: "Knowledge Graph Embeddings: From Theory to Practice"
description: "ECAI 2020 Tutorials, September 4th 2020, Friday, 13:45-17:00 CEST"
markdown: kramdown
url: "http://Kge-Tutorial-ECAI-2020.github.io"
